version: "3"
services:
  postgresbase:
    image: "postgres:13"
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=teddyzxcv
      - POSTGRES_DB=postgrestest
    volumes:
      - "data-volume:/var/lib/postgresql/data"
volumes:
  data-volume:
